### ISSUE TITLE
Errors when initializing

### ISSUE THREAD

**Issue by cristianmtr** [GreyZmeem/python-logging-loki#10]
I am seeing some errors in the console. This happens erratically

```
Traceback (most recent call last):
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/site-packages/logging_loki/handlers.py", line 81, in emit
    self.emitter(record, self.format(record))
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/site-packages/logging_loki/emitter.py", line 57, in __call__
    raise ValueError("Unexpected Loki API response status code: {0}".format(resp.status_code))
ValueError: Unexpected Loki API response status code: 400
Call stack:
  File "/home/cristian/apps/pycharm-2019.2.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 770, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/logging/handlers.py", line 1479, in _monitor
    self.handle(record)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/logging/handlers.py", line 1462, in handle
    handler.handle(record)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/site-packages/logging_loki/handlers.py", line 83, in emit
    self.handleError(record)
Message: 'No retry needed.'
```

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/site-packages/logging_loki/handlers.py", line 81, in emit
    self.emitter(record, self.format(record))
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/site-packages/logging_loki/emitter.py", line 57, in __call__
    raise ValueError("Unexpected Loki API response status code: {0}".format(resp.status_code))
ValueError: Unexpected Loki API response status code: 400
Call stack:
  File "/home/cristian/apps/pycharm-2019.2.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 770, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/logging/handlers.py", line 1479, in _monitor
    self.handle(record)
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/logging/handlers.py", line 1462, in handle
    handler.handle(record)
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/home/cristian/anaconda3/envs/chatbot/lib/python3.6/site-packages/logging_loki/handlers.py", line 83, in emit
    self.handleError(record)
Message: 'Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section'
Arguments: None
```

**Comment by cristianmtr** [comment]
@GreyZmeem 

I am also getting this error some times. Not sure if related

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/site-packages/logging_loki/handlers.py", line 81, in emit
    self.emitter(record, self.format(record))
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/site-packages/logging_loki/emitter.py", line 57, in __call__
    raise ValueError("Unexpected Loki API response status code: {0}".format(resp.status_code))
ValueError: Unexpected Loki API response status code: 400
Call stack:
  File "/home/cristian/apps/pycharm-2019.2.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 770, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/logging/handlers.py", line 1479, in _monitor
    self.handle(record)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/logging/handlers.py", line 1462, in handle
    handler.handle(record)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/home/cristian/anaconda3/envs/actionserver/lib/python3.6/site-packages/logging_loki/handlers.py", line 83, in emit
    self.handleError(record)
Message: 'Event request-created.secrets-manager.GetSecretValue: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fb8322d42b0>>'
Arguments: None
```

**Comment by gs202** [comment]
This might happen when you have double / `//` at the url

**Comment by cristianmtr** [comment]
You mean at the end? I don't have that

Here's my config:

```python
def init_loki_handler():
    loki_user = os.getenv("LOKI_USERNAME")
    loki_password = os.getenv("LOKI_PASSWORD")

    if loki_user and loki_password:
        return logging_loki.LokiHandler(
            url="https://logs-prod-us-central1.grafana.net/loki/api/v1/push",
            tags={"application": "XXXXXXXXXXXXXXX},
            auth=(loki_user, loki_password),
            version="1",
        )
    else:
        logger.warning(
            f"No username and password provided for Loki. Use 'LOKI_USERNAME' and 'LOKI_PASSWORD'"
        )
        return None
```

**Comment by cristianmtr** [comment]
I also tried `version="0"`

**Comment by gs202** [comment]
@cristianmtr i had the same error when used something like that `url="http://my_host//loki/api/v1/push"` 
But it's not your case as i can see
