### ISSUE TITLE
Extra tags cause Loki to internal error

### ISSUE THREAD

**Issue by bclermont** [GreyZmeem/python-logging-loki#3]
I tried the following

```python
import logging
import logging_loki

handler = logging_loki.LokiHandler(
    url="https://$MYSERVER/api/prom/push",
    tags={"application": "bruno-test"},
)

logger = logging.getLogger("bruno-logger")
logger.addHandler(handler)
logger.error(
    "Something happened",
)
```

and that works:

![Screenshot 2019-09-25 at 13 36 13](https://user-images.githubusercontent.com/474302/65572127-a7388400-df99-11e9-9ff6-10b7041ce8f7.png)

but I do:

```python
logger.error(
    "Something happened",
    extra={"tags": {
        "bruno-tag": "xxx"
    }},
)
```

I get

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/logging_loki/handlers.py", line 72, in emit
    raise ValueError("Unexpected Loki API response status code: %s" % resp.status_code)
ValueError: Unexpected Loki API response status code: 500
Call stack:
  File "a.py", line 14, in <module>
    "bruno-tag": "xxx"
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/local/lib/python3.7/site-packages/logging_loki/handlers.py", line 74, in emit
    self.handleError(record)
```

on Loki server side:

```
level=warn ts=2019-09-25T05:34:17.971104105Z caller=logging.go:49 traceID=5ff3ee51249a93 msg="POST /api/prom/push (500) 242.786µs Response: \"parse error at line 1, col 71: syntax error: unexpected IDENTIFIER, expecting = or != or =~ or !~\\n\" ws: false; Accept: */*; Accept-Encoding: gzip, deflate; Content-Length: 205; Content-Type: application/json; User-Agent: python-requests/2.22.0; X-Forwarded-For: 10.164.0.21; X-Forwarded-Host: $MYSERVER; X-Forwarded-Port: 443; X-Forwarded-Proto: https; X-Forwarded-Server: traefik-7856fd8df5-n4t8d; X-Real-Ip: 10.164.0.21; "
```

i'm running loki official build from docker image `grafana/loki:v0.3.0`

**Comment by GreyZmeem** [comment]
@bclermont 
I believe this is due to the hyphen in the "bruno-tag". I'm not sure that loki supports tags that have a hyphen. It may be worthwhile to replace the hyphen with an underscore when sending a request to loki.
